### ISSUE TITLE
Issue with cloudfoundry service in usecase.json

### ISSUE THREAD

**Issue by rui1610** [SAP-samples/btp-setup-automator#255]
Hi Rui- This issue still persists this morning, and I cannot proceed- 
ERROR      : service >saplaunchpad< with plan >standard< in region >eu10< IS NOT AVAILABLE

These are the three entitlements I'm trying to add in right now, and I also have an error about the 'standard' plan for CF is not available, only free, yet when I configure manually, I have the standard option.

```
{
            "name": "sapappstudio",
            "plan": "standard-edition",
            "category": "APPLICATION",
            "entitleonly": true
        },
        {
            "name": "cloudfoundry",
            "plan": "standard",
            "category": "ENVIRONMENT",
            "entitleonly": true
        },
        {
            "name": "saplaunchpad",
            "plan": "standard",
            "category": "APPLICATION",
            "entitleonly": true
        }

```
Another issue I encountered this morning, trying to add CloudFoundry:

```
[2022-10-13 15:35:28] INFO       : Check for available environment landscapes in subaccount >07f9e26d-ed9d-44e8-bcb4-8d19c9da3aaa< and region >eu10< (try 5 - trying again in 3s)
[2022-10-13 15:35:28] RUN COMMAND: btp --format json list accounts/available-environment --subaccount '07f9e26d-ed9d-44e8-bcb4-8d19c9da3aaa'
[2022-10-13 15:35:34] ERROR      : Traceback (most recent call last):

NoneType: None
[2022-10-13 15:35:34] ERROR      :   File "/home/user/./btpsa", line 32, in <module>
    myBtpUseCase.initialize_environments()

NoneType: None
[2022-10-13 15:35:34] ERROR      :   File "/home/user/libs/python/btp_cli.py", line 287, in initialize_environments
    self.create_environments()

NoneType: None
[2022-10-13 15:35:34] ERROR      :   File "/home/user/libs/python/btp_cli.py", line 323, in create_environments
    envLandscape = selectEnvironmentLandscape(

NoneType: None
[2022-10-13 15:35:34] ERROR      :   File "/home/user/libs/python/btp_cli.py", line 1488, in selectEnvironmentLandscape
    environment["name"] + "< for >" + region + "<")

NoneType: None
[2022-10-13 15:35:34] ERROR      : TypeError: 'BTPSERVICE' object is not subscriptable

NoneType: None
[2022-10-13 15:35:34] ERROR      : 'BTPSERVICE' object is not subscriptable
NoneType: None
```

Unsure if they are bugs, or simply my lack of knowing how everything is keyed in, even when looking at docs.  I can start logging issues thought!

My teams end goal is an end-to-end automation for starting with the global account creation, and then the sub account with entitlements, users, permissions (which are also not applying), CF org members, etc.   It may be either A, I'm missing knowledge, or B, it's not possible.  We are migrating all of our former COLO customers onto BTP, and the manual effort is staggering..

_Originally posted by @dachtera in https://github.com/SAP-samples/btp-setup-automator/discussions/20#discussioncomment-3870173_

**Comment by lechnerc77** [comment]
The problems with the setup described in this issue and the original discussion cannot be reproduced. From my understanding the goal is to create a Cloud Foundry space as well as two app subscriptions with the option `entitleonly`.

Using the following setup this works:

`parameters.json`:

```json
{
  "$schema": "https://raw.githubusercontent.com/SAP-samples/btp-setup-automator/main/libs/btpsa-parameters.json",
  "usecasefile": "usecases/released/default.json",
  "region": "us10",
  "globalaccount": "<Put your global account ID here>",
  "myemail": "<Put your email here>",
  "loginmethod": "sso",
  "subaccountname": null,
  "cfspacename": "development"
}
```

`default.json`:

```json
{
    "$schema": "https://raw.githubusercontent.com/SAP-samples/btp-setup-automator/main/libs/btpsa-usecase.json",
    "aboutThisUseCase": {
        "name": "Default use case on how to show how btp-setup-automator works",
        "description": "This usecase sets up various services and app subscriptions on SAP BTP",
        "author": "rui.nogueira@sap.com",
        "testStatus": "tested successfully",
        "usageStatus": "READY TO BE USED"
    },
    "services": [
        {
            "name": "sapappstudio",
            "plan": "standard-edition",
            "category": "APPLICATION",
            "entitleonly": true
        },
        {
            "name": "SAPLaunchpad",
            "plan": "standard",
            "category": "APPLICATION",
            "entitleonly": true
        }
    ]
}
```

Be aware of: 
- issue #256 that was fixed with PR #258 (fetch latest sources or newest Docker image)
- issue #257 for us10 - the behavior is currently under investigation 

I close this issue as the reported error cannot be reproduced.

**Comment by dachtera** [comment]
Hello,

Here are my json files - I note that my only big change is we are not in the US datacenter, but EU.  My same issue here persists.

parameters.json
```
{
  "$schema": "https://raw.githubusercontent.com/SAP-samples/btp-setup-automator/main/libs/btpsa-parameters.json",
  "usecasefile": "usecases/released/hca.json",
  "region": "eu10",
  "globalaccount": "[removed]",
  "myemail": "tim.dachtera@sap.com",
  "loginmethod": "sso",
  "subaccountname": "dev",
  "cfspacename": "dev",
  "envvariables": {
    "BTPSA_YOUR_OWN_ENV_VARIABLE1": "Hi! I'm BTPSA!",
    "BTPSA_YOUR_OWN_ENV_VARIABLE2": "How are you doing?",
    "BTPSA_YOUR_OWN_ENV_VARIABLE3": "You can use these variables in any command within the `executeBeforeAccountSetup` and `executeAfterAccountSetup` section by accessing (and manupulating) them as an OS environment variables"
  },
  "myusergroups": [
    {
      "name": "admins",
      "members": [
        "tim.dachtera@sap.com",
        "nathan.snyder@sap.com"
      ]
    },
    {
      "name": "developers",
      "members": [
        "robert.felter@sap.com",
        "guilherme.sales@sap.com",
        "navia.samal@sap.com",
        "thomas.nagel@sap.com",
        "charlie.siemens@sap.com"
      ]
    },
    {
      "name": "auditors",
      "members": [
        "tim.snyder@sap.com"
      ]
    },
    {
      "name": "testers",
      "members": [
        "danny.mudd@sap.com"
      ]
    }
  ]
}
```
I copied the values for the default file as you noted, yet my same issue remains with the persistence of the status check for subscription.


hca.json
```
{
    "$schema": "https://raw.githubusercontent.com/SAP-samples/btp-setup-automator/main/libs/btpsa-usecase.json",
    "aboutThisUseCase": {
        "name": "Default use case on how to show how btp-setup-automator works",
        "description": "This usecase sets up various services and app subscriptions on SAP BTP",
        "author": "rui.nogueira@sap.com",
        "testStatus": "tested successfully",
        "usageStatus": "READY TO BE USED"
    },
     "services": [
{
            "name": "SAPLaunchpad",
            "plan": "standard",
            "category": "APPLICATION",
            "entitleonly": true
        }        
],
    "assignrolecollections": [
        {
            "name": "Global Account Administrator",
            "type": "account",
            "level": "global account",
            "assignedUserGroupsFromParameterFile": [
                "admins"
            ]
        },
        {
            "name": "Subaccount Administrator",
            "type": "account",
            "level": "sub account",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "developers"
            ]
        },
        {
            "name": "Subaccount Service Administrator",
            "type": "account",
            "level": "sub account",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "developers"
            ]
        },
        {
            "name": "SpaceManager",
            "type": "cloudfoundry",
            "level": "space",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "developers"
            ]
        },
        {
            "name": "SpaceDeveloper",
            "type": "cloudfoundry",
            "level": "space",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "developers"
            ]
        },                  
        {
            "name": "SpaceAuditor",
            "type": "cloudfoundry",
            "level": "space",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "developers"
            ]
        },
        {
            "name": "OrgManager",
            "type": "cloudfoundry",
            "level": "org",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "testers"
            ]
        },
        {
            "name": "OrgAuditor",
            "type": "cloudfoundry",
            "level": "org",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "auditors"
            ]
        },
        {
            "name": "Business_Application_Studio_Administrator",
            "type": "cloudfoundry",
            "level": "space",
            "assignedUserGroupsFromParameterFile": [
                "admins",
                "developers"
            ]
        }
    ]
}
```
